baseurl = "https://jstaf.github.io/hpc-intro/"
languageCode = "en-us"
metadataformat = "yaml"
title = "Intro to HPC"
theme = "hugo-alabaster-theme"

disqusShortname = ""
googleAnalytics = ""

[params]
	name = "Intro to HPC"
	description = "Running jobs on a cluster"

	github_user   = "jstaf"
	github_repo   = "hpc-intro"
	github_banner = false

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"

[params.sidebar]
	logo = "favicon.ico"


	github_button  = false
	travis_button  = false
	codecov_button = false
	gratipay = ""

	show_relations = true

[params.footer]
	copyright = "[Jeff Stafford](https://github.com/jstaf)"
	show_powered_by = true
